name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  Test-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: chmod +x clean-script.sh
      - run: sudo ./clean-script.sh
      - run: echo "all good"
      Test-script:
    runs-on: nixos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: chmod +x clean-script.sh
      - run: sudo ./clean-script.sh
      - run: echo "all good"
      Test-script:
    runs-on: arch-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: chmod +x clean-script.sh
      - run: sudo ./clean-script.sh
      - run: echo "all good"
      Test-script:
    runs-on: fedora-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: chmod +x clean-script.sh
      - run: sudo ./clean-script.sh
      - run: echo "all good"